### ISSUE TITLE
Jira encountered an error: [components] - data was not an array

### ISSUE THREAD

**Issue by tomcart90** [replicaJunction/PSJira#34] opened 2016-08-04 15:58 UTC
Hey,

When attempting to create an issue with the component field set I'm receiving the following error:

_WARNING: JIRA returned HTTP error 400 - BadRequest
Resolve-JiraError : Jira encountered an error: [components] - data was not an array
At C:\windows\system32\windowspowershell\v1.0\Modules\PSJira\Functions\Internal\Invoke-JiraMethod.ps1:99 char:13
-             Resolve-JiraError $result -WriteError
-             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
  - FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-JiraError_

The command i'm using is as follows: 

New-JiraIssue -Project TestProject -IssueType Story -Summary "Test Issue" -Description "Test Desc" -Pr
iority 1 -Reporter "me" -Fields @{'components'='RTST'}

I've also tried replacing 'RTST' with a powershell array, but no joy :(

Also - thanks for this work, it's going to be extremely helpful once I get it working!

Cheers,
Tom

**Comment by replicaJunction** [comment] 2016-08-21 05:23
Hmm. Could you run this command, double-check and sanitize it if need be, and post the results?

`Get-JiraIssueCreateMetadata -Project TestProject -IssueType Story`

**Comment by replicaJunction** [comment] 2016-10-04 01:35
Hi tomcart90 - is this still going on in the latest version of PSJira? I'd be happy to take a look if you could post the results of the command in the previous comment.

**Comment by kalrix** [comment] 2016-10-14 22:13
Hey replicaJunction,

Not OP but I am still encountering this issue in version 1.2.5.135. 

Here is the output i have for the Metadata command:

```
Get-JiraIssueCreateMetadata -Project 'Project' -IssueType Problem -Credential $cred

Id              : components
Name            : Component/s
Schema          : @{type=array; items=component; system=components}
HasDefaultValue : False
Required        : False
AllowedValues   : {@{'self'='https://example.jira.com/rest/api/2/component/11258';'id'='11258';'name'='Access Request';'description'='Access requests'},@{'self'='https://example.jira.com/rest/api/2/component/11261';'id'='11261';'name'='Maintenance';'description'='General environment or infrastructure maintenance'},@{'self'='https://example.jira.com/rest/api/2/component/11263';'id'='11263';'name'='Trouble Ticket';'description'='Any and all support issues'}}
Operations      : {add, set, remove}
```

Not sure if this is helpful at all but from what i read it looks like the components field requires the object to be passed in a array in []s

https://answers.atlassian.com/questions/9379363/how-to-add-component-while-creating-an-issue-via-jira-rest-api

**Comment by aopub** [comment] 2016-11-24 17:01
Hi. I am new to GitHub and this forum, like @kalrix  I could reproduce this issue. I suspect the issue is general to fields that expect an array of values. As the "components" field is mandatory on my system this is definitely blocking for me.
Is someone looking at this issue, or are there known workarounds?

**Comment by replicaJunction** [comment] 2016-12-30 23:46
Hey @aopub, sorry for the delay in getting back to you. I must have missed your comment!

I've got the Components field [documented now](http://psjira.readthedocs.io/en/latest/custom_fields.html#components) over on the new documentation hub. Basically, @kalrix is correct - Components needs to be an array.

I'm going to go ahead and close this issue for now, since the issue has been documented, but feel free to re-open it or create a new one if you're still having trouble!

**Closed by replicaJunction** 2016-12-30 23:46 UTC
